## первая версия файла
---
repo_url: "https://repo.manticoresearch.com/repository/manticoresearch_jammy/dists/jammy/main/binary-amd64"
manticore_version: "6.3.6-24080214-593045790"
manticore_packages:
  - name: "manticore-server"
    type: "amd64"
  - name: "manticore-server-core"
    type: "amd64"
  - name: "manticore"
    type: "amd64"
  - name: "manticore-tools"
    type: "amd64"
  - name: "manticore-common"
    type: "all"
  - name: "manticore-dev"
    type: "all"

manticore_columnar_version: "2.3.0-24052206-88a01c3"
columnar_packages:
  - name: "manticore-columnar-lib"
    type: "amd64"

manticore_backup_version: "1.3.8-24052208-57fc406"
backup_packages:
  - name: "manticore-backup"
    type: "all"

manticore_buddy_version:  "2.3.12-24071807-45f6b91"
buddy_packages:
  - name: "manticore-buddy"
    type: "all"
manticore_executor_version: "1.1.12-24071807-0565a65"
executor_packages:
  - name: "manticore-executor"
    type: "amd64"
manticore_icudata_version: "65l"
icudata_packages:
  - name: "manticore-icudata"
manticore_galera_version: "3.37"
galera_packages:
  - name: "manticore-galera"
    type: "amd64"
manticore_tzdata_version: "1.0.0-240522-a8aa66e"
tzdata_packages:
  - name: "manticore-tzdata"
    type: "all"