    base_url: "https://repo.manticoresearch.com/repository/manticoresearch_jammy/dists/jammy/main/binary-amd64"
    download_dir: "/home/ansible/manticore"

    all_packages:
      - { name: "manticore-server", version: "6.3.6-24080214-593045790", type: "amd64" }
      - { name: "manticore-server-core", version: "6.3.6-24080214-593045790", type: "amd64" }
      - { name: "manticore", version: "6.3.6-24080214-593045790", type: "amd64" }
      - { name: "manticore-tools", version: "6.3.6-24080214-593045790", type: "amd64" }
      - { name: "manticore-commonr", version: "6.3.6-24080214-593045790", type: "all" }
      - { name: "manticore-dev", version: "6.3.6-24080214-593045790", type: "all" }
      - { name: "manticore-columnar-lib", version: "2.3.0-24052206-88a01c3", type: "amd64" }
      - { name: "manticore-backup", version: "1.3.8-24052208-57fc406", type: "all" }
      - { name: "manticore-buddy", version: "2.3.12-24071807-45f6b91", type: "all" }
      - { name: "manticore-executor", version: "1.1.12-24071807-0565a65", type: "amd64" }
      - { name: "manticore-icudata", version: "65l" }
      - { name: "manticore-galera", version: "3.37", type: "amd64" }
      - { name: "manticore-tzdata", version: "1.0.0-240522-a8aa66e", type: "all" }